backend:
  name: github
  repo: iMioiMio/iMioiMio.github.io  # 仓库名，大小写完全一致
  branch: master                         # 默认分支，如果你的仓库是 master，请改成 master
  auth_scope: repo                     # 允许访问仓库

media_folder: "assets/images"         # 上传图片存放位置
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"                   # 仓库里实际存放页面的文件夹
    create: true
    slug: "{{slug}}"                   # 自动生成 URL
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Posts"
    folder: "_posts"                   # 文章存放文件夹
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
